=== AlejandroBlancoV/marcas/2021-2022/aRECUPERACION/ExamenB/Soluciones/cartelera.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<!-- Versión con referencias (ref)
por tanto es necesario añadir como atributo al esquema
la linea que explica el espacio de nombres
xlmns:car="http://www.cine.com/"
((si no hubiese ref no seria necesario)) -->


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.cine.com/"
           xmlns:car="http://www.cine.com/"
           elementFormDefault="qualified">

    <!-- Definiciones de tipos          -->

    <xs:complexType name="tipoPelicula">
        <xs:sequence>
            <xs:element ref="car:titulo"/>
            <xs:element ref="car:titulo_original" minOccurs="0"/>
            <xs:element ref="car:nacionalidad"/>
            <xs:element ref="car:genero"/>
            <xs:choice>
                <xs:element ref="car:clasificacion"/>
                <xs:element ref="car:sin_clasificar"/>
            </xs:choice>
            <xs:element ref="car:sinopsis"/>
            <xs:element ref="car:director"/>
            <xs:element ref="car:reparto"/>
            <xs:element ref="car:web" minOccurs="0"/>
            <xs:element ref="car:cartel" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="codigo" type="xs:positiveInteger"/>
        <xs:attribute name="duracion" type="xs:positiveInteger"/>
        <xs:attribute name="año" type="xs:positiveInteger" default="2003"/>
    </xs:complexType>

    <xs:complexType name="tipoReparto">
        <xs:sequence>
            <xs:element ref="car:actor" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoClasificacion">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="edad" type="car:tipoEdad" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="tipoEdad">
        <xs:restriction base="xs:string">
            <xs:enumeration value="tp"/>
            <xs:enumeration value="8"/>
            <xs:enumeration value="12"/>
            <xs:enumeration value="16"/>
            <xs:enumeration value="18"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- ================================ -->
    <!-- Elementos de tipo simple    -->
    <!-- ================================ -->
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="titulo_original" type="xs:string"/>
    <xs:element name="nacionalidad" type="xs:string"/>
    <xs:element name="genero" type="xs:string"/>
    <xs:element name="clasificacion" type="car:tipoClasificacion"/>
    <xs:element name="sin_clasificar"/>
    <xs:element name="sinopsis" type="xs:string"/>
    <xs:element name="director" type="xs:string"/>
    <xs:element name="reparto" type="car:tipoReparto"/>
    <xs:element name="web" type="xs:string"/>
    <xs:element name="cartel" type="xs:string"/>
    <xs:element name="actor" type="xs:string"/>





    <!-- ================================ -->
    <!-- Elementos de tipo complejo    -->
    <!-- ================================ -->

    <xs:element name="cartelera">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="car:pelicula"  maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pelicula" type="car:tipoPelicula"/>

</xs:schema>

=== AlejandroBlancoV/marcas/2021-2022/aRECUPERACION/ExamenB/Soluciones/cartelera.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
(CUANDO MARCA COMO ERROR EL ESPACIO DE NOMBRES
SOLO TENEMOS QUE DARLE EN LA OPCION IGNORA RECURSO EXTERNO)
-->

<car:cartelera  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="cartelera.xsd http://www.cine.com/"
                xmlns:car="http://www.cine.com/">

    <car:pelicula codigo="1" duracion="152" año="2002">
        <car:titulo>AQUELLAS JUERGAS UNIVERSITARIAS</car:titulo>
        <car:titulo_original>Old School</car:titulo_original>
        <car:nacionalidad>Estados Unidos</car:nacionalidad>
        <car:genero>Comedia</car:genero>
        <car:clasificacion edad="tp"/>
        <car:sinopsis>
            Mitch, Frank y Beanie son tres amigos treintañeros cuyas vidas no son
            exactamente lo que esperaban. Mitch tiene una novia ninfómana que se mete en
            la cama con el primero que agarra. Frank se ha casado y su matrimonio nada
            tiene que ver con las juergas salvajes que organizaban años atrás. Y Beanie es
            un padre de  familia que se muere por recuperar su alocada juventud. Pero las
            cosas cambian cuando Beanie sugiere que creen su propia fraternidad, en la
            nueva casa que Mitch tiene junto al campus de la universidad. Una ocasión para
            revivir tiempos gloriosos, hacer nuevos amigos y de volver a sus viejas,
            salvajes y desmadradas juergas de estudiantes.
        </car:sinopsis>
        <car:director>Todd Philips</car:director>
        <car:reparto>
            <car:actor>Luke Wilson</car:actor>
            <car:actor>Will Farrel</car:actor>
            <car:actor>Vince Vaughn</car:actor>
        </car:reparto>
        <car:web>http://www.uip.es</car:web>
        <car:cartel>caratulas/Aquellas juergas.jpg</car:cartel>
    </car:pelicula>
    <car:pelicula codigo="17" duracion="06">
        <car:titulo>EL ORO DE MOSCÚ</car:titulo>
        <car:nacionalidad>España</car:nacionalidad>
        <car:genero>Comedia</car:genero>
        <car:sin_clasificar/>
        <car:sinopsis>
            Por una extraña coincidencia del destino, alguien recibe una información
            extraconfidencial de un anciano en sus últimos segundos de vida: el secreto
            mejor guardado de la Historia. El receptor, un trabajador de hospital, se lo
            comunica secretamente a un supuesto amigo. Ambos inician una aventura
            rocambolesca y llena de misterio. Ante la inutilidad de sus intentos y muy a
            su pesar, tienen que recurrir a otras personas que así mismo van cayendo en el
            pozo sin fondo que conlleva descifrar el enigma.
        </car:sinopsis>
        <car:director>Jesús Bonilla</car:director>
        <car:reparto>
            <car:actor>Jesús Bonilla</car:actor>
            <car:actor>Santiago Segura</car:actor>
            <car:actor>Alfredo Landa</car:actor>
            <car:actor>Concha Velasco</car:actor>
            <car:actor>Antonio Resines</car:actor>
            <car:actor>Gabino Diego, María Barranco</car:actor>
            <car:actor>María Barranco</car:actor>
        </car:reparto>
    </car:pelicula>
</car:cartelera>
