=== AlejandroBlancoV/marcas/2022-2023/Alejandro/XML/Apuntes/ejercicioOCHO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="listacursos" type="tCurso"/>

    <xsd:complexType name="tCurso">
        <xsd:sequence>
            <xsd:element name="curso" type="tAlumno" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tAlumno">
        <xsd:sequence>
            <xsd:group ref="tDatos"/>
            <xsd:element name="listaAsignaturas" type="tListaAsignaturas"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tListaAsignaturas">
        <xsd:sequence>
            <xsd:element name="nombre" type="tAsignatura" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tAsignatura">
        <xsd:sequence>
            <xsd:element name="nombre" type="xsd:string"/>
            <xsd:element name="profesor" type="tProfesor"/>
        </xsd:sequence>
        <xsd:attribute name="codigo" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="tProfesor">
        <xsd:sequence>
            <xsd:element name="NRP" type="xsd:string"/>
            <xsd:element name="nombre" type="xsd:string"/>
            <xsd:element name="apellidoUno" type="xsd:string"/>
            <xsd:element name="apellidoDos" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:group name="tDatos">
        <xsd:sequence>
            <xsd:element name="dni" type="xsd:string"/>
            <xsd:element name="nombre" type="xsd:string"/>
            <xsd:element name="apellidoUno" type="xsd:string"/>
            <xsd:element name="apellidoDos" type="xsd:string" minOccurs="0"/>
        </xsd:sequence>
    </xsd:group>

</xsd:schema>

=== AlejandroBlancoV/marcas/2022-2023/Alejandro/XML/Apuntes/ejercicioOCHO.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listacursos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="ejercicioOCHO.xsd">
<curso>
    <dni>123a</dni>
    <nombre>Antonio</nombre>
    <apellidoUno>Rodriguez</apellidoUno>
    <listaAsignaturas>
        <nombre codigo="QP3">
            <nombre>Matematicas</nombre>
            <profesor>
                <NRP>12R</NRP>
                <nombre>Luis</nombre>
                <apellidoUno>Fernandez</apellidoUno>
            </profesor>
        </nombre>
    </listaAsignaturas>
</curso>
</listacursos>
