=== AlejandroBlancoV/marcas/2022-2023/Alejandro/XML/Apuntes/ejercicioCINCO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:complexType name="atributosVC">
        <xsd:sequence>
            <xsd:element name="fechafinpago" minOccurs="0" maxOccurs="1" type="xsd:date"/>
            <xsd:element name="cantidad" minOccurs="1" maxOccurs="1" type="xsd:float"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="atributosVI">
        <xsd:sequence>
            <xsd:element name="cantidad" minOccurs="1" maxOccurs="1" type="xsd:float"/>
            <xsd:element name="divisa" minOccurs="1"  maxOccurs="1" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="tipoventa">
        <xsd:sequence>
            <xsd:choice>
                <xsd:element name="ventacredito" minOccurs="1" maxOccurs="1" type="atributosVC"/>
                <xsd:element name="ventainmediata" minOccurs="1" maxOccurs="1" type="atributosVI"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ventas">
        <xsd:sequence>
            <xsd:element name="venta" minOccurs="1" maxOccurs="unbounded" type="tipoventa"/>
        </xsd:sequence>
    </xsd:complexType>



    <xsd:element name="listaventas" type="ventas"/>

</xsd:schema>

=== AlejandroBlancoV/marcas/2022-2023/Alejandro/XML/Apuntes/ejercicioCINCO.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listaventas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="ejercicioCINCO.xsd">
    <venta>
        <ventacredito>
            <fechafinpago>2023-07-21</fechafinpago>
            <cantidad>31</cantidad>
        </ventacredito>
    </venta>
    <venta>
        <ventainmediata>
            <cantidad>12</cantidad>
            <divisa>Euro</divisa>
        </ventainmediata>
    </venta>
    <venta>
        <ventacredito>
            <cantidad>2</cantidad>
        </ventacredito>
    </venta>
    <venta>
        <ventainmediata>
            <cantidad>21</cantidad>
            <divisa>Libra</divisa>
        </ventainmediata>
    </venta>
    <venta>
        <ventainmediata>
            <cantidad>38</cantidad>
            <divisa>DÃ³lar</divisa>
        </ventainmediata>
    </venta>
</listaventas>
