=== AlejandroBlancoV/marcas/2022-2023/Alejandro/XML/Apuntes/ejercicioCUATRO.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:complexType name="atributos">
        <xsd:sequence>
            <xsd:element name="importe" type="xsd:float" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="comprador" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="vendedor" type="xsd:string" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="codigo" type="xsd:int" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="fecha" type="xsd:date" minOccurs="0" maxOccurs="1"/>

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="numventas">
        <xsd:sequence>
            <xsd:element name="venta" minOccurs="1" maxOccurs="unbounded" type="atributos"/>
        </xsd:sequence>
    </xsd:complexType>



    <xsd:element name="listaventas" type="numventas"/>


</xsd:schema>

=== AlejandroBlancoV/marcas/2022-2023/Alejandro/XML/Apuntes/ejercicioCUATRO.xml
<?xml version="1.0" encoding="UTF-8" ?>
<listaventas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="ejercicioCUATRO.xsd">
    <venta>
        <importe>205</importe>
        <comprador>Don Antonio</comprador>
        <vendedor>Pepe</vendedor>
        <codigo>102</codigo>
    </venta>
    <venta>
        <importe>23</importe>
        <comprador>Angel</comprador>
        <vendedor>Miguel</vendedor>
        <codigo>078</codigo>
        <fecha>2022-03-12</fecha>
    </venta>
</listaventas>
